insert into magnit.Options (Option_Id, Option, Score) values (1, 'Developer', 1);
insert into magnit.Options (Option_Id, Option, Score) values (2, 'QA', 1);
insert into magnit.Options (Option_Id, Option, Score) values (3, 'Business Analyst', 1);
insert into magnit.Options (Option_Id, Option, Score) values (4, 'Product Owner', 1);
insert into magnit.Options (Option_Id, Option, Score) values (5, 'DevOps', 1);
insert into magnit.Options (Option_Id, Option, Score) values (6, 'Very Dissatisfied', 1);
insert into magnit.Options (Option_Id, Option, Score) values (7, 'Dissatisfied', 2);
insert into magnit.Options (Option_Id, Option, Score) values (8, 'Satisfied', 3);
insert into magnit.Options (Option_Id, Option, Score) values (9, 'Very Satisfied', 4);
insert into magnit.Options (Option_Id, Option, Score) values (10, 'Greatly Satisfied', 5);
insert into magnit.Options (Option_Id, Option, Score) values (11, 'Design', 1);
insert into magnit.Options (Option_Id, Option, Score) values (12, 'Implementation', 1);
insert into magnit.Options (Option_Id, Option, Score) values (13, 'Bug Fixing', 1);
insert into magnit.Options (Option_Id, Option, Score) values (14, 'Production Support', 1);
insert into magnit.Options (Option_Id, Option, Score) values (15, 'Manual testing', 1);
insert into magnit.Options (Option_Id, Option, Score) values (16, 'Performance Testing', 1);
insert into magnit.Options (Option_Id, Option, Score) values (17, 'Automation', 1);
insert into magnit.Options (Option_Id, Option, Score) values (18, 'Test Suite Creation And Execution', 1);
insert into magnit.Options (Option_Id, Option, Score) values (19, 'Interaction With Client', 1);
insert into magnit.Options (Option_Id, Option, Score) values (20, 'Soliciting Requirements', 1);
insert into magnit.Options (Option_Id, Option, Score) values (21, 'Communication with Product Owners', 1);
insert into magnit.Options (Option_Id, Option, Score) values (22, 'Other', 1);
insert into magnit.Options (Option_Id, Option, Score) values (23, 'Learning the Market and Customer Needs', 1);
insert into magnit.Options (Option_Id, Option, Score) values (24, 'Interaction with Business', 1);
insert into magnit.Options (Option_Id, Option, Score) values (25, 'Interaction with Leads', 1);
insert into magnit.Options (Option_Id, Option, Score) values (26, 'Prioritising Backlog', 1);
insert into magnit.Options (Option_Id, Option, Score) values (27, 'Incident Management and Root Cause Analysis', 1);
insert into magnit.Options (Option_Id, Option, Score) values (28, 'Implementing and Monitoring Infrastructure', 1);
insert into magnit.Options (Option_Id, Option, Score) values (29, 'Trouble Shooting', 1);
insert into magnit.Options (Option_Id, Option, Score) values (30, 'Deploying CI/CD Tools', 1);
